Grammar changes
s4u/slf4j-mock pull request #64
Opened 2021-03-29 20:14 UTC by fredster33

2021-03-29 20:37 UTC, slawekjaranowski requested changes
please also look at `src/site/markdown/index.md.vm`

2021-03-29 20:54 UTC, fredster33 commented on README.md
> +Yet another way to test logging in to applications which use SLF4J.
I believe that `to` is required, because `to` addresses the verb `test`.

2021-03-29 21:05 UTC, slawekjaranowski commented on README.md
> +Yet another way to test logging in to applications which use SLF4J.
I think about: `logging in -> to <- applications` - but I'm not native speaker so I can wrong

2021-03-29 21:09 UTC, fredster33 commented on README.md
> +Yet another way to test logging in to applications which use SLF4J.
Could you clarify please?

2021-03-30 17:47 UTC, slawekjaranowski commented on README.md
> +Yet another way to test logging in to applications which use SLF4J.
I see two options:
1. Yet another way to test logging in to applications which use SLF4J.
2. Yet another way to test logging in applications which use SLF4J.

why 1 is better than 2?

2021-03-30 18:43 UTC, fredster33 commented on README.md
> +Yet another way to test logging in to applications which use SLF4J.
"Logging in" requires a subject to apply to, and "to" I think is the transition to the subject.

2021-04-05 21:14 UTC, slawekjaranowski commented on README.md
> +Yet another way to test logging in to applications which use SLF4J.
Here `logging` is used as process which produce trace/debug message, some system log and this is happened `in` application. 

We don't thing about `loging in` as changing permission to have access to application.

2021-04-06 16:11 UTC, fredster33 commented on README.md
> +Yet another way to test logging in to applications which use SLF4J.
All right, undid my edit for that section.

2021-04-06 16:53 UTC, slawekjaranowski commented
please also look at `src/site/markdown/index.md.vm`

2021-06-16 21:44 UTC, closed without merging